name: Angular Staff Management CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️ Setup Node.js (adjust to your Angular version)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3️ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️ Lint check
      - name: Run lint
        run: npm run lint --if-present

      # 5️ Run unit tests
      - name: Run unit tests
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

      # 6️ Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration=production

      # 7️ Upload build artifacts (optional)
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/